
name: Bastion State Manager

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      power:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Turn bastion server on or off'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  bastion-power:
    name: Turn on/off Bastion
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Action # Print the environment variables and the event payload. Useful for developing or debugging GitHub Actions.
      uses: hmarr/debug-action@v1.0.0 # https://github.com/hmarr/debug-action
      
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_PROD }}
        
    - name: Scale up/down Bastion ASG
      run: |
        aws autoscaling update-auto-scaling-group \
        	--auto-scaling-group-name ${{ secrets.BASTION_ASG_NAME }} \
        	--desired-capacity ${{ github.event.inputs.power }}
