# This is a basic workflow that is manually triggered

name: contrib workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      read_respository_owner:
        description: The owner/organization name the repository belongs to
        required: true
      read_respository_repo:
        description: The name of the repository to query contributors from
        required: true
      write_repository_owner:
          description: The owner/organization name the repository belongs to
          required: false
          default: hackforla
      write_repository_repo:
          description: The name of the repository to create the issue in
          required: true
          default: governance

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let contributors = await github.repos.listContributors({
              owner: `${{ github.event.inputs.read_respository_owner }}`,
              repo: `${{ github.event.inputs.read_respository_repo }}`,
              per_page: 100
            });
            contributors = contributors.data
            console.log(`\`\`\`\n@${contributors.map(contributor => contributor.login).join(', @')}\n\`\`\` `);
            
            let issueCreated = await github.issues.create({
              owner: `${{ github.event.inputs.write_repository_owner }}`,
              repo: `${{ github.event.inputs.write_repository_repo }}`,
              title: `${{ github.event.inputs.write_repository_repo }} repository wants to change its license type`,
              body: `\`\`\`\n@${contributors.map(contributor => contributor.login).join(', @')}\n\`\`\` `
            });
            
            console.log(issueCreated);
