name: Update wins data

# Run this action every day at 4am Pacific (12 am UTC)
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'

jobs:
  wins-data-grabber:
    runs-on: ubuntu-latest
    
    if: github.repository == 'akibrhast/github-actions-test'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install script requirements
      run: pip install -r utils/wins-cleaner-requirements.txt
    
    - name: Save wins-data.json
      env:
          WINS_API_KEY: ${{ secrets.WINS_API_KEY }}
      run: python utils/wins-cleaner.py
    
    - name: Prettify Code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,json,py}

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        # Optional glob pattern of files which should be added to the commit
        file_pattern: data.json

        commit_message: Update wins data

        # Optional commit user and author settings
        commit_author: GitHub Actions Bot <akibrhast>

